import Head from "next/head";
import { useState} from "react";
import ClickerDiv from "~/components/clicker-parts/ClickerDiv";
import Upgrades from "~/components/Upgrades";

 const Home: React.FC = () => {
  const [chaos, setChaos] = useState<number>(0);
  const [qntd, setQntd] = useState<number>(1);

  return (
    <>
      <Head>
        <title>PoE Clicker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen grid-cols-4 bg-zinc-700">
        <ClickerDiv setChaos={setChaos} chaos={chaos} qntd={qntd}/>
        <Upgrades chaos={chaos} setQntd={setQntd} qntd={qntd}/>
      </main>
    </>
  );
}

export default Home;